### ISSUE TITLE
Use LPMP to solve a linear assignment problem?

### ISSUE THREAD

**Issue by angshine** [LPMP/LPMP#17]
Is it possible to use LPMP to solve a linear assignment problem, instead of the full graph matching?

**Comment by pawelswoboda** [comment]
You can of course, but then it is even better to directly use a combinatorial solver, see here: https://lemon.cs.elte.hu/trac/lemon .
You have to construct a network flow problem (construct bipartite graph) and use one of the lemon solvers from above. This should scale better!

**Comment by angshine** [comment]
@pawelswoboda Thanks for the quick reply! However, I want to keep the ability to differentiate through the solver. Is it possible to differentiate the lemon solve?

**Comment by pawelswoboda** [comment]
The differentiating through the solver is a technique independent of the
solver, see https://github.com/martius-lab/blackbox-backprop . The
differentiation is already used for graph matching so it might be easier to
take the LPMP build. If you only have linear assignment costs, my solver
will be fast and exact, since I use a combinatorial solver inside. So you
might directly use ist as well. Of course, there is some overhead attacked
to my solver that you might get rid of by reimplementing it directly with
just a combinatorial solver.

Cheers,
Paul
